--- #YAML:1.0
name: DBD::mysqlPPrawSjis
abstract: Pure Perl MySQL driver for raw ShiftJIS
version: 0.08
author:
  - INABA Hitoshi <ina@cpan.org>
license: perl
distribution_type: script
requires:
  Archive::Tar: 0.072
  Carp: 0
  Compress::Zlib: 1.03
  DBI: 1.14
  File::Basename: 2.6
  File::Copy: 2.02
  File::Path: 1.0401
  Net::MySQL: 0.08
  Test: 1.122
  Test::Harness: 1.1602
  perl: 5.005_03
build_requires:
  Test: 1.122
urls:
  license: http://dev.perl.org/licenses/
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
generated_by: INABA Hitoshi <ina@cpan.org>
